import {
  ClerkProvider,
  //SignInButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto", // CSS variable to use in styles
});

export const metadata: Metadata = {
  title: "VITMUN'25",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en" suppressHydrationWarning className={`${roboto.variable}`}>
        <body>
         
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
