name: Deploy Application

on:
  workflow_run:
    workflows:
      - Node.js CI # Match the name of the first workflow
    types:
      - completed # Trigger only after the first workflow completes
    branches:
      - main # Trigger only for the main branch

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the first workflow succeeded
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "ADMIN_USERNAME=${{secrets.ADMIN_USERNAME}}" >> .env
          echo "ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}}" >> .env

      - name: Build and Run Docker Compose
        run: |
          docker compose down
          docker compose up --build -d