name: Deploy Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Code
        run: git pull

      - name: Stop and Remove Containers
        run: docker compose down

      - name: Build and Start Containers
        run: docker compose up --build 
