name: Manage Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manage-docker-containers:
    runs-on: self-hosted
    steps:
      - name: Debug environment
        run: |
          echo "User: $(whoami)"
          echo "Current Directory: $(pwd)"
          echo "Docker version:"
          docker --version
          echo "Docker Compose version:"
          docker-compose --version
          echo "List running containers:"
          docker ps

      - name: Stop all running containers
        run: |
          echo "Stopping all running Docker containers..."
          docker ps -q | xargs -r docker stop

      - name: Run docker-compose down
        run: |
          echo "Stopping and removing Docker Compose containers..."
          docker-compose down
        working-directory: /munsoc/vitmun-25

      - name: Run docker-compose up
        run: |
          echo "Starting Docker Compose services..."
          docker-compose up -d
        working-directory: /munsoc/vitmun-25
