name: Manage Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manage-docker-containers:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop all running containers
        run: |
          echo "Stopping all running Docker containers..."
          docker ps -q | xargs -r docker stop

      - name: Run docker-compose down
        run: |
          echo "Stopping and removing Docker Compose containers..."
          docker-compose down
        working-directory: ./your-docker-compose-directory

      - name: Run docker-compose up
        run: |
          echo "Starting Docker Compose services..."
          docker-compose up -d
        working-directory: ./your-docker-compose-directory
